//#ifndef SQLUSAGEPLUGIN_GLOBAL_H
#ifndef SQLUSAGEPLUGIN_GLOBAL_H
#define SQLUSAGEPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SQLUSAGEPLUGIN_LIBRARY)
#  define SQLUSAGEPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SQLUSAGEPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SQLUSAGEPLUGIN_GLOBAL_H
