#ifndef THEMEMANAGER_GLOBAL_H
#define THEMEMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(THEMEMANAGER_LIBRARY)
#  define THEMEMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define THEMEMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // THEMEMANAGER_GLOBAL_H
