#ifndef POKEMONONLINESTATSPLUGIN_GLOBAL_H
#define POKEMONONLINESTATSPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(POKEMONONLINESTATSPLUGIN_LIBRARY)
#  define POKEMONONLINESTATSPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define POKEMONONLINESTATSPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // POKEMONONLINESTATSPLUGIN_GLOBAL_H
