#ifndef SMOGONPLUGIN_GLOBAL_H
#define SMOGONPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SMOGONPLUGIN_LIBRARY)
#  define SMOGONPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SMOGONPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SMOGONPLUGIN_GLOBAL_H

