#ifndef SETTINGSPLUGIN_GLOBAL_H
#define SETTINGSPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SETTINGSPLUGIN_LIBRARY)
#  define SETTINGSPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SETTINGSPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SETTINGSPLUGIN_GLOBAL_H
