#ifndef CHESSPLUGIN_GLOBAL_H
#define CHESSPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CHESSPLUGIN_LIBRARY)
#  define CHESSPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CHESSPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CHESSPLUGIN_GLOBAL_H
