#ifndef POKEMONINFO_GLOBAL_H
#define POKEMONINFO_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(POKEMONINFO_LIBRARY)
#  define POKEMONINFOSHARED_EXPORT Q_DECL_EXPORT
#else
#  define POKEMONINFOSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // POKEMONINFO_GLOBAL_H
