#ifndef WEBSERVERPLUGIN_GLOBAL_H
#define WEBSERVERPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(WEBSERVERPLUGIN_LIBRARY)
#  define WEBSERVERPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define WEBSERVERPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // WEBSERVERPLUGIN_GLOBAL_H
