#ifndef BATTLEMANAGER_GLOBAL_H
#define BATTLEMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BATTLEMANAGER_LIBRARY)
#  define BATTLEMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BATTLEMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BATTLEMANAGER_GLOBAL_H
