#ifndef DESIGNERPLUGIN_GLOBAL_H
#define DESIGNERPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DESIGNERPLUGIN_LIBRARY)
#  define DESIGNERPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DESIGNERPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DESIGNERPLUGIN_GLOBAL_H
