#ifndef POKEMONSTRUCTS_GLOBAL_H
#define POKEMONSTRUCTS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(POKEMONSTRUCTS_LIBRARY)
#  define POKEMONSTRUCTSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define POKEMONSTRUCTSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // POKEMONSTRUCTS_GLOBAL_H
