#ifndef DATABASEEDITOR_GLOBAL_H
#define DATABASEEDITOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DATABASEEDITOR_LIBRARY)
#  define DATABASEEDITORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DATABASEEDITORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DATABASEEDITOR_GLOBAL_H
