#ifndef QRCODEPLUGIN_GLOBAL_H
#define QRCODEPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QRCODEPLUGIN_LIBRARY)
#  define QRCODEPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QRCODEPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QRCODEPLUGIN_GLOBAL_H
