#ifndef CLIENTSCRIPTING_GLOBAL_H
#define CLIENTSCRIPTING_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CLIENTSCRIPTING_LIBRARY)
#  define CLIENTSCRIPTINGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CLIENTSCRIPTINGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CLIENTSCRIPTING_GLOBAL_H
